### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by akomylator** [lubeda/EsphoMaTrix#20]
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 825, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 812, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/esphome/esphome/__main__.py", line 366, in command_run
    exit_code = write_cpp(config)
  File "/esphome/esphome/__main__.py", line 159, in write_cpp
    generate_cpp_contents(config)
  File "/esphome/esphome/__main__.py", line 171, in generate_cpp_contents
    CORE.flush_tasks()
  File "/esphome/esphome/core/__init__.py", line 613, in flush_tasks
    self.event_loop.flush_tasks()
  File "/esphome/esphome/coroutine.py", line 245, in flush_tasks
    next(task.iterator)
  File "/esphome/esphome/__main__.py", line 151, in wrapped
    await coro(conf)
  File "/config/esphome/.esphome/external_components/66a08d7e/components/ehmtx/__init__.py", line 560, in to_code
    espImage.IMAGE_TYPE["RGB565"],
KeyError: 'RGB565'

**Comment by lubeda** [comment]
check your esphome version. the rgb565 image type was introduced 2022.5.0 so you need at least this version.
