### ISSUE TITLE
Problem Compiling

### ISSUE THREAD

**Issue by pollierer** [lubeda/EsphoMaTrix#25]
Using latest Home Assistant Version  & ESPHome with a D1 Mini I get a compile error:

INFO Reading configuration /config/esphome/matrix.yaml...
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 825, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 812, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/esphome/esphome/__main__.py", line 326, in command_compile
    exit_code = write_cpp(config)
  File "/esphome/esphome/__main__.py", line 159, in write_cpp
    generate_cpp_contents(config)
  File "/esphome/esphome/__main__.py", line 171, in generate_cpp_contents
    CORE.flush_tasks()
  File "/esphome/esphome/core/__init__.py", line 613, in flush_tasks
    self.event_loop.flush_tasks()
  File "/esphome/esphome/coroutine.py", line 245, in flush_tasks
    next(task.iterator)
  File "/esphome/esphome/__main__.py", line 151, in wrapped
    await coro(conf)
  File "/config/esphome/.esphome/external_components/66a08d7e/components/ehmtx/__init__.py", line 560, in to_code
    espImage.IMAGE_TYPE["RGB565"],
KeyError: 'RGB565'

Any hints for me? I used one single Icon in the yaml, tried different file formats (gif, png) but as far as I understand this should not be the issue here. I tried to replace the Key RGB585 with RGB24, which throws another error. (I have to admit I have no clue what I am doing there ;) )

If I replace the Key with RGB24 in the code, this error is thrown:

INFO Reading configuration /config/esphome/matrix.yaml...
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Compiling app...
Processing matrix (board: d1_mini; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|-- <NeoPixelBus> 2.6.9
|   |-- <SPI> 1.0
Compiling /data/matrix/.pioenvs/matrix/src/esphome/components/ehmtx/EHMTX_icons.cpp.o
Compiling /data/matrix/.pioenvs/matrix/lib67b/ESP8266WiFi/ESP8266WiFiGratuitous.cpp.o
Compiling /data/matrix/.pioenvs/matrix/lib67b/ESP8266WiFi/ESP8266WiFiMulti.cpp.o
Compiling /data/matrix/.pioenvs/matrix/lib67b/ESP8266WiFi/ESP8266WiFiSTA-WPS.cpp.o
Compiling /data/matrix/.pioenvs/matrix/lib67b/ESP8266WiFi/ESP8266WiFiSTA.cpp.o
Compiling /data/matrix/.pioenvs/matrix/lib67b/ESP8266WiFi/ESP8266WiFiScan.cpp.o
Compiling /data/matrix/.pioenvs/matrix/lib67b/ESP8266WiFi/WiFiClient.cpp.o
src/esphome/components/ehmtx/EHMTX_icons.cpp: In member function 'void esphome::EHMTX_Icon::next_frame()':
src/esphome/components/ehmtx/EHMTX_icons.cpp:33:20: error: 'prev_frame' is not a member of 'esphome::display::Animation'
   33 |         Animation::prev_frame();
      |                    ^~~~~~~~~~
Compiling /data/matrix/.pioenvs/matrix/lib67b/ESP8266WiFi/WiFiClientSecureBearSSL.cpp.o
*** [/data/matrix/.pioenvs/matrix/src/esphome/components/ehmtx/EHMTX_icons.cpp.o] Error 1
========================= [FAILED] Took 15.85 seconds =========================

I would be happy for anything pointing me into the right direction. Thank you! :)

**Comment by pollierer** [comment]
Thank you lubeda, problem solved! My fault was, I did not recognize auto updates of esphome was turned off. Updated/Installed the latest version. It´s working now. My Version was 2022.3. Thanks again!

**Comment by pollierer** [comment]
closing
